name: Java CI/CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'
      working-directory: ./server
    - name: Build with Maven
      run: mvn clean install -DskipTests=true
      working-directory: ./server
    - name: Run tests
      run: mvn test
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build Docker image
      run: docker build -t it-one:alpha .
    - name: Tag Docker image
      run: docker tag myapp:latest isofinly/it-one:alpha
    - name: Push Docker image
      run: docker push isofinly/it-one:alpha