name: Java CI/CD Pipeline 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'
      
    - name: Build with Maven
      working-directory: ./server
      run: mvn clean install -DskipTests=true

    - name: Run tests
      working-directory: ./server
      run: mvn test

    - name: Login to Docker Hub
      working-directory: ./server
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      working-directory: ./server
      run: docker build -t it-one:alpha .

    - name: Tag Docker image
      working-directory: ./server
      run: docker tag myapp:latest isofinly/it-one:alpha

    - name: Push Docker image
      working-directory: ./server
      run: docker push isofinly/it-one:alpha